### ISSUE TITLE
dask failing

### ISSUE THREAD

**Issue by jangorecki** [h2oai/db-benchmark#92]
```
import dask.dataframe as dd
Traceback (most recent call last):
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 15, in <module>
    from .io import (
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/dataframe/io/__init__.py", line 15, in <module>
    from .csv import read_csv, to_csv, read_table, read_fwf
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/dataframe/io/csv.py", line 22, in <module>
    from ...bytes import read_bytes, open_files
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/bytes/__init__.py", line 10, in <module>
    "fsspec is required to use any file-system functionality."
ImportError: fsspec is required to use any file-system functionality. Please install using
conda install -c conda-forge 'fsspec>=0.3.3'
or
pip install 'fsspec>=0.3.3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 57, in <module>
    raise ImportError(str(e) + "\n\n" + msg)
ImportError: fsspec is required to use any file-system functionality. Please install using
conda install -c conda-forge 'fsspec>=0.3.3'
or
pip install 'fsspec>=0.3.3'

Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  pip install dask[dataframe] --upgrade  # or pip install
```
maybe due to conda that has been installed to run cudf, or a dependency has changed and was not automatically installed during upgrade?

**Comment by jangorecki** [comment]
installing fsspec did resolve problem, dask is again on benchplot

**Comment by rojour** [comment]
I am also facing the same issue.
I am able to install dask[complete] in both python 2.7 and 3.5.5

When running dask.dataframe from python 2.7 there are no issues, but when running from python 3.5.5 I get that fsspec needs to be installed (and I am sure that it is there).

Am I missing something here?

**Comment by isnbh0** [comment]
> I am also facing the same issue.
> I am able to install dask[complete] in both python 2.7 and 3.5.5
> 
> When running dask.dataframe from python 2.7 there are no issues, but when running from python 3.5.5 I get that fsspec needs to be installed (and I am sure that it is there).
> 
> Am I missing something here?

I had the same problem.

In my case it was solved by:
- installing the bz2 library (`sudo apt-get install libbz2-dev` for my Ubuntu 16.04)
- reinstalling python3
